export const styles = [{name:"American Light Lager"},
{name:"American Lager"},
{name:"Cream Ale"},
{name:"American Wheat Beer"},
{name:"International Pale Lager"},
{name:"International Amber Lager"},
{name:"International Dark Lager"},
{name:"Czech Pale Lager"},
{name:"Czech Premium Pale Lager"},
{name:"Czech Amber Lager"},
{name:"Czech Dark Lager"},
{name:"Munich Helles"},
{name:"Festbier"},
{name:"Helles Bock"},
{name:"German Leichtbier"},
{name:"Kölsch"},
{name:"German Helles Exportbier"},
{name:"German Pils"},
{name:"Märzen"},
{name:"Rauchbier"},
{name:"Dunkles Bock"},
{name:"Vienna Lager"},
{name:"Altbier"},
{name:"Pale Kellerbier"},
{name:"Amber Kellerbier"},
{name:"Munich Dunkel"},
{name:"Schwarzbier"},
{name:"Doppelbock"},
{name:"Eisbock"},
{name:"Baltic Porter"},
{name:"Weissbier"},
{name:"Dunkles Weissbier"},
{name:"Weizenbock"},
{name:"Ordinary Bitter"},
{name:"Best Bitter"},
{name:"Strong Bitter"},
{name:"British Golden Ale"},
{name:"Australian Sparkling Ale"},
{name:"English IPA"},
{name:"Dark Mild"},
{name:"British Brown Ale"},
{name:"English Porter"},
{name:"Scottish Light"},
{name:"Scottish Heavy"},
{name:"Scottish Export"},
{name:"Irish Red Ale"},
{name:"Irish Stout"},
{name:"Irish Extra Stout"},
{name:"Sweet Stout"},
{name:"Oatmeal Stout"},
{name:"Tropical Stout"},
{name:"Foreign Extra Stout"},
{name:"British Strong Ale"},
{name:"Old Ale"},
{name:"Wee Heavy"},
{name:"English Barleywine"},
{name:"Blonde Ale"},
{name:"American Pale Ale"},
{name:"American Amber Ale"},
{name:"California Common"},
{name:"American Brown Ale"},
{name:"American Porter"},
{name:"American Stout"},
{name:"Imperial Stout"},
{name:"American IPA"},
{name:"Belgian IPA"},
{name:"Black IPA"},
{name:"Brown IPA"},
{name:"Red IPA"},
{name:"Rye IPA"},
{name:"White IPA"},
{name:"Double IPA"},
{name:"American Strong Ale"},
{name:"American Barleywine"},
{name:"Wheatwine"},
{name:"Berliner Weisse"},
{name:"Flanders Red Ale"},
{name:"Oud Bruin"},
{name:"Lambic"},
{name:"Gueuze"},
{name:"Fruit Lambic"},
{name:"Witbier"},
{name:"Belgian Pale Ale"},
{name:"Bière de Garde"},
{name:"Belgian Blond Ale"},
{name:"Saison"},
{name:"Belgian Golden Strong Ale"},
{name:"Trappist Single"},
{name:"Belgian Dubbel"},
{name:"Belgian Tripel"},
{name:"Belgian Dark Strong Ale"},
{name:"Gose"},
{name:"Kentucky Common"},
{name:"Lichtenhainer"},
{name:"London Brown Ale"},
{name:"Piwo Grodziskie"},
{name:"Pre-Prohibition Lager"},
{name:"Pre-Prohibition Porter"},
{name:"Roggenbier"},
{name:"Sahti"},
{name:"Brett Beer"},
{name:"Mixed-Fermentation Sour Beer"},
{name:"Wild Specialty Beer"},
{name:"Fruit Beer"},
{name:"Fruit and Spice Beer"},
{name:"Specialty Fruit Beer"},
{name:"Spice, Herb, or Vegetable Beer"},
{name:"Autumn Seasonal Beer"},
{name:"Winter Seasonal Beer"},
{name:"Alternative Grain Beer"},
{name:"Alternative Sugar Beer"},
{name:"Classic Style Smoked Beer"},
{name:"Specialty Smoked Beer"},
{name:"Wood-Aged Beer"},
{name:"Specialty Wood-Aged Beer"},
{name:"Clone Beer"},
{name:"Mixed-Style Beer"},
{name:"Experimental Beer"},
]
